/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.Admin;

import java.awt.Button;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.Timer;


/**
 *
 * @author Umesh Saranga
 */
public class Admin_main extends javax.swing.JFrame {

    /**
     * Creates new form Admin_main
     */
    public Admin_main() {
        initComponents();
        showDate();
        showTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnMonthlyReports = new javax.swing.JLabel();
        btnDailyReports = new javax.swing.JLabel();
        btnAddItems = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Admin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, -1, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTime.setText("Time");
        jPanel2.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setText("Date");
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 109, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/Admin/home2.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 10, 150));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 10));

        btnMonthlyReports.setBackground(new java.awt.Color(190, 190, 190));
        btnMonthlyReports.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnMonthlyReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMonthlyReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/Admin/home_Report.png"))); // NOI18N
        btnMonthlyReports.setText("  Monthly Reports                    ");
        btnMonthlyReports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnMonthlyReports.setOpaque(true);
        btnMonthlyReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMonthlyReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMonthlyReportsMouseExited(evt);
            }
        });
        jPanel2.add(btnMonthlyReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 190, 25));

        btnDailyReports.setBackground(new java.awt.Color(190, 190, 190));
        btnDailyReports.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnDailyReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDailyReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/Admin/home_Report.png"))); // NOI18N
        btnDailyReports.setText("   Daily Reports                         ");
        btnDailyReports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnDailyReports.setOpaque(true);
        btnDailyReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDailyReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDailyReportsMouseExited(evt);
            }
        });
        jPanel2.add(btnDailyReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 190, 25));

        btnAddItems.setBackground(new java.awt.Color(190, 190, 190));
        btnAddItems.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnAddItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop/Admin/home_Add_Item.png"))); // NOI18N
        btnAddItems.setText("  Add Item                                  ");
        btnAddItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnAddItems.setOpaque(true);
        btnAddItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddItemsMouseExited(evt);
            }
        });
        jPanel2.add(btnAddItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 190, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        jPanel1.setBackground(new java.awt.Color(49, 58, 115));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 670, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMonthlyReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyReportsMouseEntered
        setBtnColour(btnMonthlyReports);
    }//GEN-LAST:event_btnMonthlyReportsMouseEntered

    private void btnMonthlyReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonthlyReportsMouseExited
        resetBtnColour(btnMonthlyReports);
    }//GEN-LAST:event_btnMonthlyReportsMouseExited

    private void btnDailyReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyReportsMouseEntered
        setBtnColour(btnDailyReports);
    }//GEN-LAST:event_btnDailyReportsMouseEntered

    private void btnDailyReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDailyReportsMouseExited
         resetBtnColour(btnDailyReports);
    }//GEN-LAST:event_btnDailyReportsMouseExited

    private void btnAddItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemsMouseClicked
        
    }//GEN-LAST:event_btnAddItemsMouseClicked

    private void btnAddItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemsMouseEntered
        setBtnColour(btnAddItems);
    }//GEN-LAST:event_btnAddItemsMouseEntered

    private void btnAddItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemsMouseExited
        resetBtnColour(btnAddItems);
    }//GEN-LAST:event_btnAddItemsMouseExited

    private void showDate() {
        Date date = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        lblDate.setText(df.format(date));
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a"); // use HH for het time in 24 hour format
                lblTime.setText(df.format(date));
            }

            //@Override
            //public void actionPerformed(ActionEvent e) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           // }
        }).start();
      
    }
     private void setBtnColour(JLabel label) {
        label.setBackground(new Color(150, 150, 150));
    }

    private void resetBtnColour(JLabel label) {
        label.setBackground(new Color(190, 190, 190));
    }

    private void setButtonColour(Button button) {
        button.setBackground(new Color(0, 153, 0));
        button.setForeground(new Color(255, 255, 255));

    }

    private void resetButtonColour(Button button) {
        button.setBackground(new Color(240, 240, 240));
        button.setForeground(new Color(0, 0, 0));

    }

    private void setLableColour(JLabel lbl) {
        lbl.setBackground(new Color(106, 116, 145));

    }

    private void resetLableColour(JLabel lbl) {
        lbl.setBackground(new Color(9, 18, 72));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddItems;
    private javax.swing.JLabel btnDailyReports;
    private javax.swing.JLabel btnMonthlyReports;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

    //private void setBtnColour(JLabel btnReport) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    //private void resetBtnColour(JLabel btnReport) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
